# Title of the document
title: "Pandas Profiling Report"

# Metadata
dataset:
  description: "Preços e volumes, para todos os produtos, de todos os negócios realizados na BBCE. Estes negócios são realizados em plataforma de negociação (BBCE), de forma online e em real-time pelos agentes de mercado e disponibilizados para os agentes participantes da plataforma."
  creator: "BBCE - Balcão Brasileiro de Comercialização de Energia"
  author: "Volt Robotics"
  copyright_holder: ""
  copyright_year: ""
  url: ""

variables:
  descriptions: {
    'id': 'Chave de identificação, única para cada operação',
    'data': 'Dia da operação',
    'time': 'Horário da operação',
    'tipo': 'Natureza da operação',
    'produto': 'Produto ao qual a operação está relacionada',
    'qtde_mwm': 'MW médio',
    'preco': 'Valor negociad',
    'qtde_mwh': 'MWh',
    'local': 'Local de realização da operação - balcão ou boleta',
    'tend': 'Tipo de operação - compra ou venda',
    'data_completa': 'Data e hora da operação',
    'year': 'Ano da operação',
    'flag_datetime': '1 indica que o registro viola regras de consistência para data e hora, 0 indica que o registro está de acordo com as regras',
    'media_preco': 'Preço pédio por produto por dia para cada tipo',
    'flag_preco': '1 indica uma variação abrupta de preço em 24h'
  }

# infer dtypes
infer_dtypes: true

# Show the description at each variable (in addition to the overview tab)
show_variable_description: true

# Number of workers (0=multiprocessing.cpu_count())
pool_size: 0

# Show the progress bar
progress_bar: true

# Per variable type description settings
vars:
    num:
        quantiles:
              - 0.05
              - 0.25
              - 0.5
              - 0.75
              - 0.95
        skewness_threshold: 20
        low_categorical_threshold: 5
        # Set to zero to disable
        chi_squared_threshold: 0.999
    cat:
        length: true
        characters: true
        words: true
        cardinality_threshold: 50
        n_obs: 5
        # Set to zero to disable
        chi_squared_threshold: 0.999
        coerce_str_to_date: false
        redact: false
        histogram_largest: 50
    bool:
        n_obs: 3
        # string to boolean mapping dict
        mappings:
            t: true
            f: false
            yes: true
            no: false
            y: true
            n: false
            true: true
            false: false
    file:
        active: false
    image:
        active: false
        exif: true
        hash: true
    path:
        active: false
    url:
        active: false

# Sort the variables. Possible values: "ascending", "descending" or null (leaves original sorting)
sort: null

# which diagrams to show
missing_diagrams:
    bar: true
    matrix: true
    heatmap: true
    dendrogram: true

correlations:
    pearson:
      calculate: false
      warn_high_correlations: true
      threshold: false
    spearman:
      calculate: false
      warn_high_correlations: false
      threshold: 0.9
    kendall:
      calculate: false
      warn_high_correlations: false
      threshold: 0.9
    phi_k:
      calculate: false
      warn_high_correlations: false
      threshold: 0.9
    cramers:
      calculate: false
      warn_high_correlations: true
      threshold: 0.9


# Bivariate / Pairwise relations
interactions:
  targets: []
  continuous: false

# For categorical
categorical_maximum_correlation_distinct: 100

report:
  precision: 10

# Plot-specific settings
plot:
    # Image format (svg or png)
    image_format: "svg"
    dpi: 800

    scatter_threshold: 1000

    correlation:
        cmap: 'RdBu'
        bad: '#000000'

    missing:
        cmap: 'RdBu'
        # Force labels when there are > 50 variables
        # https://github.com/ResidentMario/missingno/issues/93#issuecomment-513322615
        force_labels: true

    pie:
        # display a pie chart if the number of distinct values is smaller or equal (set to 0 to disable)
        max_unique: 2000

    histogram:
        x_axis_labels: true

        # Number of bins (set to 0 to automatically detect the bin size)
        bins: 30

        # Maximum number of bins (when bins=0)
        max_bins: 250

# The number of observations to show
n_obs_unique: 5
n_extreme_obs: 5
n_freq_table_max: 10

# Use `deep` flag for memory_usage
memory_deep: false

# Configuration related to the duplicates
duplicates:
    head: 10
    key: "# duplicates"

# Configuration related to the samples area
samples:
    head: 10
    tail: 10
    random: 0

# Configuration related to the rejection of variables
reject_variables: true

# When in a Jupyter notebook
notebook:
    iframe:
        height: '800px'
        width: '100%'
        # or 'src'
        attribute: 'srcdoc'

html:
    # Minify the html
    minify_html: true

    # Offline support
    use_local_assets: true

    # If true, single file, else directory with assets
    inline: true

    # Show navbar
    navbar_show: true

    # Assets prefix if inline = true
    assets_prefix: null

    # Styling options for the HTML report
    style:
      theme: united
      logo: ""
      primary_color: "#d34615"

    full_width: true
